development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ncaa_db_dev
  pool: 5
  username: root
  password: root
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ncaa_db_test
  pool: 5
  username: root
  password: root

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: ncaa_db_prod
  pool: 5
  username: root
  password: root
